# Generated by Django 5.2.4 on 2025-07-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPenduduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('rt', models.CharField(max_length=3)),
                ('rw', models.CharField(max_length=3)),
                ('tanggal_lahir', models.DateField()),
            ],
        ),
    ]
