# Generated by Django 5.2.4 on 2025-07-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapenduduk',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_penduduk/'),
        ),
    ]
