# Generated by Django 5.2.4 on 2025-07-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekap', '0002_datapenduduk_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapenduduk',
            name='no_kk',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
