# Generated by Django 5.2.4 on 2025-07-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekap', '0004_histori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histori',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=20),
        ),
    ]
